---
- name: Configure and start EC2 instance
  amazon.aws.ec2_instance:
    name: web-server
    count: 1
    image_id: ami-06c4be2792f419b7b
    instance_type: t2.small
    key_name: aws-key-pair
    security_group: http-sec-group
    network:
      assign_public_ip: true
    tags: {type: web, env: staging}
    wait: true
  register: ec2

- name: Wait for SSH to become available
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 30
    timeout: 300
  loop: "{{ ec2.instances }}"
  
- name: Add the instances to the staging groups
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groupname:
      - staging
  loop: "{{ ec2.instances }}"