---
- name: Configure and start EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    count: "{{ instance_count }}"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    tags: {type: web, env: staging}
    wait: true
  register: ec2

- name: Wait for SSH to become available
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 30
    timeout: 300
  loop: "{{ ec2.instances }}"
  
- name: Add the instances to the staging groups
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groupname:
      - "{{ group_name }}"
  loop: "{{ ec2.instances }}"