---
- name: Install apache
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Remve apache redhat
      yum:
        name: apache2
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove apache debian
      apt:
        name: apache2
        state: absent
      when: ansible_os_family == "Debian" 
