---
- name: create users
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: delete users
      user:
        name: "{{ item }}"
        state: absent 
        groups: sudo
      loop:
        - dadang
        - budi
        - joko