---
- name: Provision an EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Configure and start EC2 instance
      amazon.aws.ec2_instance:
        name: web1
        count: 2
        image_id: ami-015f72d56355ebc27
        instance_type: t2.micro
        key_name: aws-key-pair
        security_group: http-sec-group
        network:
          assign_public_ip: true
        tags: {type: web, env: staging}
        wait: true
      register: ec2

    - name: Add the instances to the staging groups
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname:
          - staging
      loop: "{{ ec2.instances }}"







