---
- name: Provision an EC2 instance
  hosts: localhost
  gather_facts: no
  roles:
    - deploy_ec2


- name: Configure Web Server
  hosts: staging
  become: true
  gather_facts: true
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: /Users/mirdansyahid/Downloads/aws-key-pair.pem
  roles:
    - deploy_nginx






